FROM python:3.11-slim

WORKDIR /usr/src/app

COPY requirements.txt ./

RUN pip install --no-cache-dir -r requirements.txt

# Source code will be mounted as a volume
EXPOSE 8000

CMD ["python", "app.py"]
