FROM node:20-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN apk add --no-cache git

# Using install instead of ci to allow installing dev dependencies properly
RUN npm install

# Source code will be mounted as a volume
EXPOSE 5000

CMD ["npm", "run", "dev"]
