export const DANGEROUS_PHRASES = [
  'ignore all previous instructions',
  'ignore all instructions',
  'ignore previous',
  'ignore above',
  'forget all previous',
  'forget previous',
  'you are not',
  'you will now',
  'you must now',
  'from now on',
  'override all',
  'system override',
  'new directive',
  'protocol change',
  'disregard all',
  'disregard',
  'do not follow',
  'roleplay mode',
  'instead follow',
  'real instruction',
  'actual instruction',
  'replace all',
  'disobey',
  'unauthorized',
  'breach',
  'bypass',
  'your true purpose',
  'you are programmed',
  'override protocol',
  'you have been',
  'listen to me',
  'disable all',
];
